[tools]
go = "latest"
java = "corretto-17"
ktlint = "latest"
kubectl = "latest"
lua = "latest"
maven = "latest"
node = "20"
pnpm = "10"
pre-commit = "latest"
rust = "latest"
starship = "latest"
telepresence = "2.18"
tree-sitter = "latest"
uv = "latest"
zig = "latest"
