[tools]
node = "lts"
pnpm = "latest"
maven = "latest"
java = "corretto-17"
go = "latest"
kubectl = "latest"
python = "3"
httpie-go = "latest"
rust = "latest"
zig = "latest"
bun = "latest"
telepresence = "2.18.0"
