[tools]
go = "latest"
java = "corretto-17"
ktlint = "latest"
kubectl = "latest"
lua = "latest"
maven = "latest"
node = "20"
pnpm = "9"
rust = "latest"
spark = "3.5"
telepresence = "2.18"
zig = "latest"
