[tools]
node = "20"
java = "corretto-17"
pnpm = "latest"
ktlint = "latest"
gradle = "latest"
telepresence = "2.18"
maven = "latest"
lua = "latest"
rust = "latest"
go = "latest"
starship = "latest"
neovim = "latest"
bat = "latest"
ripgrep = "latest"
tree-sitter = "latest"
bun = "latest"
deno = "latest"
zig = "latest"
kubectl = "latest"
jq = "latest"
duf = "latest"
dust = "latest"
delta = "latest"
awscli = "latest"
