#! /bin/sh

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 0

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10

bspc config border_width               2
bspc config window_gap                 10
bspc config top_padding                30
bspc config bottom_padding             0
bspc config left_padding               0
bspc config right_padding              0
bspc config single_monocle             false
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config pointer_modifier           mod4
bspc config pointer_action1            move
bspc config pointer_action2            resize_side
bspc config pointer_action3            resize_corner
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

#Fullscreen applications
bspc rule -a Vlc state=fullscreen
bspc rule -a Emacs state=tiled

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a rofi state=floating sticky=on
bspc rule -a jetbrains-toolbox state=floating sticky=on
bspc rule -a 1Password state=floating sticky=on
#bspc rule -a "battle.net.exe" state=floating

# Default workspaces for some apps
# Browsing
bspc rule -a Chromium desktop='^1'
bspc rule -a Brave-browser desktop='^1'
bspc rule -a firefox desktop='^1'

# Development
bspc rule -a code desktop='^2'
bspc rule -a jetbrains-idea desktop='^2'

# Games
bspc rule -a Steam desktop='^8'
bspc rule -a Lutris desktop='^8'
bspc rule -a "battle.net.exe" desktop='^8'

# Comms
bspc rule -a Slack desktop='^0'
bspc rule -a discord desktop='^0'

# Auto starts
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
pgrep -x picom > /dev/null || picom &
$HOME/.config/bspwm/polybar/launch.sh &
nitrogen --restore &

