[colors]
foreground = "#fffaf3"
background = "#0d0f18"
cursor_bg = "#a3b3cc"
cursor_border = "#a3b3cc"
cursor_fg = "#dcdfe4"
selection_bg = "#474e5d"
selection_fg = "#dcdfe4"

ansi = [
    "#222222",
    "#ff000f",
    "#8ce00a",
    "#ffb900",
    "#008df8",
    "#6c43a5",
    "#00d7eb",
    "#ffffff",
]
brights = [
    "#444444",
    "#ff273f",
    "#abe05a",
    "#ffd141",
    "#0092ff",
    "#9a5feb",
    "#67ffef",
    "#ffffff",
]
