[metadata]
name = 'onedarkpro_onedark_vivid'
origin_url = 'https://github.com/olimorris/onedarkpro.nvim'

[colors]
# background = '#282c34'
background = '#0d0f18'
foreground = '#abb2bf'
cursor_bg = '#d55fde'
cursor_fg = '#282c34'
selection_bg = '#d55fde'
selection_fg = '#abb2bf'
ansi = [
  '#282c34',
  '#ef596f',
  '#89ca78',
  '#e5c07b',
  '#61afef',
  '#d55fde',
  '#2bbac5',
  '#abb2bf',
]
brights = [
  '#5c6370',
  '#f38897',
  '#a9d89d',
  '#edd4a6',
  '#8fc6f4',
  '#e089e7',
  '#4bced8',
  '#c8cdd5',
]

[colors.indexed]
